name: paradrop-tools
version: 0.8.0
summary: ParaDrop development tools
description: |
  The ParaDrop tools provide the command line utilities to work with ParaDrop routers

grade: stable
confinement: strict

apps:
  pdtools:
    command: pdtools
    plugs:
      - network

parts:
  pdtools:
    plugin: python
    python-version: python2
    source: pdtools
